language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install .  
services:
  - docker
  
before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
  